version: '3.0'

services:
  mongo:
    image: 'mongo'
    ports:
        - 27017:27017
  ecourse.services.authapi:
    image: ${DOCKER_REGISTRY-}ecourseservicesauthapi
    build:
      context: .
      dockerfile: ECourse.Services.AuthAPI/Dockerfile
    depends_on:
        - mongo
    ports:
        - 4001:8080
  ecourse.services.blogapi:
    image: ${DOCKER_REGISTRY-}ecourseservicesblogapi
    build:
      context: .
      dockerfile: ECourse.Services.BlogAPI/Dockerfile
    depends_on:
        - mongo
    ports:
        - 4002:8080    
  ecourse.services.courseapi:
    image: ${DOCKER_REGISTRY-}ecourseservicescourseapi
    build:
      context: .
      dockerfile: ECourse.Services.CourseAPI/Dockerfile
    depends_on:
        - mongo
    ports:
        - 4003:8080    
  ecourse.services.orderapi:
    image: ${DOCKER_REGISTRY-}ecourseservicesorderapi
    build:
      context: .
      dockerfile: ECourse.Services.OrderAPI/Dockerfile
    depends_on:
        - mongo
    ports:
        - 4004:8080    
  ecourse.admin:
    image: ${DOCKER_REGISTRY-}ecourseadmin
    build:
      context: .
      dockerfile: Ecourse.uis.Admin/Dockerfile
    depends_on:
        - mongo
    ports:
        - 4005:8080
    
