version: '3.4'

services:
  ecourse.services.courseapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
  mongo-database:
    container_name: courseapi-mongo
    image: mongo
    ports:
      - 27017:27017
